### PR TITLE
chore(build): add CF deploy

### PR DESCRIPTION
**Pull request by asudoh**

### CODE REVIEW

**Comment by abdonrd** [comment]
Could you publish the GitHub Action as separated repository?

It would be great! We could use it in other projects too!

**Comment by asudoh** [comment]
@abdonrd My manager @jeffchew is positive on that, let me dig into this further.

**Comment by asudoh** [comment]
@abdonrd Created https://github.com/carbon-design-system/action-ibmcloud-cf, please see the README there for the details. Updated this PR to use that action.

**Comment by abdonrd** [comment]
Awesome, thanks @asudoh! 👏

**Pull request merged**
